{
 "title": "Logs Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "All Error",
   "type": "table",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=\"ad_shortener\", level=\"ERROR\"} |= ``"
    }
   ]
  },
  {
   "title": "All Warn",
   "type": "table",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "{app=\"ad_shortener\", level=\"WARN\"} |= ``"
    }
   ]
  },
  {
   "title": "All Debug",
   "type": "table",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 20 },
   "targets": [
    {
     "expr": "{app=\"ad_shortener\", level=\"DEBUG\"} |= ``"
    }
   ]
  },
  {
   "title": "All",
   "type": "table",
   "gridPos": { "h": 10, "w": 23, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "{app=\"ad_shortener\"} |= ``"
    }
   ]
  }
 ]
}